version: "3.9"

services:
  casu_backend:
    container_name: casu_backend
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "5002:5002"
    expose:
      - "5002"
    networks:
      - network1
  mongo:
    image: mongo
    restart: always
    environment:
      - MONGO_INITDB_DATABASE=admin
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    ports:
      - '27017:27017'
    expose:
      - '27017'
    networks:
      - network1
    volumes:
      - mongo:/data/db

networks:
  network1:

volumes:
  mongo:
